[package]
name = "royalbed"

[lib]
lang = "c++17"

[[test]]
lang = "c++17"
path = "tests"

[dependencies]
asio = { git = "git@gitlab.olimp.lan:github/standalone-asio.git", tag = "asio-1-18-2", interface = "asio/include" }
fmt = { git  = "git@gitlab.olimp.lan:github/fmtlib.git", tag = "7.1.3" }
gsl = { git = "git@gitlab.olimp.lan:github/gsl.git", tag = "v3.1.0", interface = "include" }
nhope = { git = "git@gitlab.olimp.lan:alekseev/nhope.git" }
nlohmann_json = {git = "git@gitlab.olimp.lan:github/nlohmann-json.git", tag = "v3.9.1"}
restbed = {git = "git@gitlab.olimp.lan:github/restbed.git", branch = "4.7-antey", links = ["restbed-static"]}
spdlog = { git = "git@gitlab.olimp.lan:gabime/spdlog.git", tag = "v1.7.0" }

[options.spdlog]
SPDLOG_FMT_EXTERNAL = true

[dev-dependencies]
gtest = { git = "git@gitlab.olimp.lan:google/googletest.git" }

[options.gtest]
gtest_force_shared_crt = "true"
