[package]
name = "royalbed"

[lib]
lang = "c++20"

[[test]]
lang = "c++20"
path = "tests"

[dependencies]
asio = { git = "git@gitlab.olimp.lan:github/standalone-asio.git", tag = "asio-1-22-0", interface = "asio/include" }
fmt = { git  = "git@gitlab.olimp.lan:github/fmtlib.git", tag = "8.1.1" }
nhope = { git = "git@gitlab.olimp.lan:alekseev/nhope.git" }
nlohmann_json = { git = "git@gitlab.olimp.lan:github/nlohmann-json.git", tag = "v3.10.5" }
spdlog = { git = "git@gitlab.olimp.lan:gabime/spdlog.git", tag = "v1.9.2" }

[options.spdlog]
SPDLOG_FMT_EXTERNAL = true

[dev-dependencies]
gtest = { git = "git@gitlab.olimp.lan:google/googletest.git", branch="file-info" }

[options.gtest]
gtest_force_shared_crt = "true"
