[package]
name = "royalbed"

[lib]
lang = "c++20"

[[test]]
lang = "c++20"
path = "tests"

[dependencies]
asio = { git = "git@gitlab.radio.voz:github/asio.git", tag = "asio-1-22-0", interface = "asio/include" }
fmt = { git  = "git@gitlab.radio.voz:github/fmtlib.git", tag = "10.0.0" }
nlohmann_json = { git = "git@gitlab.radio.voz:github/nlohmann-json.git", tag = "v3.11.2" }
spdlog = { git = "git@gitlab.radio.voz:github/spdlog.git", tag = "v1.12.0" }
nhope = {git = "git@gitlab.radio.voz:github/alekseev/nhope.git", branch = "internal"}

[options.spdlog]
SPDLOG_FMT_EXTERNAL = true

[dev-dependencies]
gtest = { git = "git@gitlab.radio.voz:github/google/googletest.git", branch = "main"}

[options.gtest]
gtest_force_shared_crt = "true"
